# name: Build and Deploy React App

# on:
#   push:
#     branches:
#       - main

# jobs:
#   job-build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: "22"

#       - name: Install dependencies
#         working-directory: ./application
#         run: npm ci

#       - name: Run Jest tests
#         working-directory: ./application
#         run: npm test

#       - name: Build React app
#         working-directory: ./application
#         run: npm run build

#       - name: Backup current out folder
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             if [ -d /var/www/clientjo/out ]; then
#               rm -rf /var/www/clientjo/out_backup
#               cp -r /var/www/clientjo/out /var/www/clientjo/out_backup
#             fi

#       - name: Remove old out folder
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             rm -rf /var/www/clientjo/out

#       - name: Copy build to server
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: "application/out/."
#           target: "/var/www/clientjo/out"
#           rm: true

#       - name: Restart Nginx
#         uses: appleboy/ssh-action@v1.0.0
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             sudo systemctl restart nginx || (echo "Failed to restart nginx" && exit 1)
#             sudo systemctl is-active nginx
#             echo "Nginx restarted successfully"

#       - name: Notify deployment success
#         run: echo "Deployment to server successful!"

name: Build and Deploy React App

on:
  push:
    branches:
      - main

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        working-directory: ./application
        run: npm ci

      - name: Run Jest tests
        working-directory: ./application
        run: npm test

      - name: Build React app
        working-directory: ./application
        run: npm run build

      - name: Create build archive
        run: tar -czf out.tar.gz -C application/out .

      - name: Backup current out folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d /var/www/clientjo/out ]; then
              rm -rf /var/www/clientjo/out_backup
              cp -r /var/www/clientjo/out /var/www/clientjo/out_backup
            fi

      - name: Remove old out folder
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/clientjo/out

      - name: Upload build archive
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "out.tar.gz"
          target: "/var/www/clientjo"

      - name: Extract archive on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /var/www/clientjo/out
            tar -xzf /var/www/clientjo/out.tar.gz -C /var/www/clientjo/out
            rm /var/www/clientjo/out.tar.gz

      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx || (echo "Failed to restart nginx" && exit 1)
            sudo systemctl is-active nginx
            echo "Nginx restarted successfully"

      - name: Notify deployment success
        run: echo "Deployment to server successful!"
