name: Deploiement Client en Production

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Exécuter les tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Installer les dépendances
        run: npm ci
        working-directory: application

      - name: Lancer les tests
        run: npm run test

  deploy:
    name: Deployer sur le serveur
    runs-on: ubuntu-latest

    steps:
      - name: etape 1 recupération du code
        uses: actions/checkout@v3

      - name: etape 2 connexion SSH au serveur
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: etape 3 Pull sur serveur
        run: |
          ssh -o StrictHostKeyChecking=no deploy@167.172.53.237 <<'EOF'
            cd ~/apps/clientjo
            git checkout main
            git pull origin main
            git pull origin main
          EOF

      - name: etape 4 Gestion Docker
        run: |
          ssh -o StrictHostKeyChecking=no deploy@167.172.53.237 <<'EOF'
            systemctl is-active docker || sudo systemctl start docker
            docker stop clientjo || true
            docker rm clientjo || true
            cd ~/apps/clientjo/application
            docker build -t clientjo .
            docker run -d --name clientjo -p 3000:3000 --restart unless-stopped clientjo
            docker image prune -af
          EOF
